version: '2'
services:
  result:
      image: 'containers101/result:update-build'
      #build: ./result
      command: node  server.js
      ports:
        - "80"
      links:
        - "db:db"
      environment:
        - OPTION_A=$VOTING_OPTION_A
        - OPTION_B=$VOTING_OPTION_B

  moshe:
    image: 'containers101/result:update-build'
    #build: ./result
    #command: node  server.js
    ports:
      - "2222"
    links:
      - "db:db"
    environment:
      - OPTION_A=$VOTING_OPTION_A
      - OPTION_B=$VOTING_OPTION_B
  worker:
    build: ./worker
    image: 'containers101/worker:update-build'
    links:
      - "db:db"
      - "redis:redis"
  redis:
    image: 'redis:alpine'
    ports:
      - "6379"
  vote:
    build: ./vote
    image: 'containers101/vote:update-build'
    command: python app.py
    ports:
      - "80"
    links:
      - "redis:redis"
    environment:
      - OPTION_A=$VOTING_OPTION_A
      - OPTION_B=$VOTING_OPTION_B
  db:
    image: 'postgres:9.4'
